### ISSUE TITLE
Favicon and title

### ISSUE THREAD

**Issue by Mickey0001** [parcel-bundler/website#11] opened 2017-12-06 01:02 UTC
Maybe add a favicon of your logo so the site looks better/more professional. 

Also the icon in front of the title seems to be broken.

![image](https://user-images.githubusercontent.com/23509920/33638996-2da64068-d9f7-11e7-86a7-71f30f698f8b.png)
![image](https://user-images.githubusercontent.com/23509920/33639002-36e9ef4e-d9f7-11e7-885e-68953dac6000.png)

**Comment by slice** [comment] 2017-12-06 01:52
Regarding the emoji in the `<title>`, it looks like an issue related to how fonts (specifically, emoji) are configured on your system — they look fine on my end.

![image](https://user-images.githubusercontent.com/4206232/33640369-fed3288a-d9e4-11e7-91f1-a377b4bdc587.png)

**Comment by Mickey0001** [comment] 2017-12-06 02:08
I only see the icon display properly in Firefox, 
Chrome, Opera and IE all show the broken icon for some reason, all are updated to the latest versions.

**Comment by vhag** [comment] 2017-12-06 14:53
The icon looks fine to me on Chrome, but I think that it is better (more idiomatic) to use a favicon instead of an icon in the title. I'm not sure how you'd use an emoji as a favicon. Maybe screenshot it?

Moving the icon from the title to an identical favicon would fix both issues.

**Comment by devongovett** [comment] 2017-12-06 19:37
We probably shouldn't use the emoji image as that is from Apple's emoji font. But we could use the parcel logo. It's available as a PSD here https://github.com/parcel-bundler/assets/blob/master/assets/avatar.psd if someone wants to make a favicon from it.

**Comment by thejameskyle** [comment] 2017-12-06 23:46
Moving to #18

**Closed by thejameskyle** 2017-12-06 23:46 UTC

**Comment by vhag** [comment] 2017-12-07 20:25
The issue is closed, but the fixing commit has not been accepted.
